config/routes.rb
Rails.application.routes.draw do

  get 'nagios/application_groups' => 'nagios#application_groups'

  scope "/payments" do
    post '/callback/:status' => 'payments#callback'
    post '/post' => 'payments#post'
    get '/redirect_to_processor' => 'payments#redirect_to_processor', :as => 'payments_redirect_to_processor'
  end

  scope "/:locale" do
    resources :online_applications do
      resources :addresses
    end

    get '/add_family_member' => 'online_applications/build#add_family_member'
    get '/add_group_member' => 'online_applications/build#add_group_member'
    resources :build, controller: 'online_applications/build'
    get '/application_groups/submitted' => 'application_groups#submitted', :as => 'application_group_submitted'
    get '/application_groups/submit' => 'application_groups#submit', :as => 'submit_application_group'
    resources :application_groups
    get '/form-unavailable' => 'home#form_unavailable', :as => 'form_unavailable'
    get '/cookies-disabled' => 'home#cookies_disabled', :as => 'cookies_disabled'
    get '/error' => 'home#error', :as => 'error'

    get '/conference_packages' => 'conference_packages#index'
  end
  get '/:locale' => 'home#index'
  get '/' => 'home#index', :as => 'home'

end

app/controllers/online_applications/build_controller.rb
class OnlineApplications::BuildController < ApplicationController

  before_filter :ensure_application_group

  include Wicked::Wizard
  steps :personal, :group, :family, :detail, :dates_and_events, :visa, :finances, :confirmation, :payment

  def show
    @step = step
    if step.to_s != 'wicked_finish'
      # Make sure that we're not skipping steps!
      redirstep = step
      while (steps.index(redirstep) - 1) >= 0
        if not has_completed?(steps[steps.index(redirstep) - 1])
          redirstep = steps[steps.index(redirstep) - 1]
        else
          break
        end
      end
      if redirstep != step
        redirect_to wizard_path(redirstep)
        return
      end

      # Catch people using the back button from the 'Registration form complete' page
      if @online_application.status.nil? and step != :personal and step != :complete
        redirect_to wizard_path(steps.first)
        return
      end
    end

    # Make sure the single/family/group radio button is prepopulated
    if @online_application.application_group.group_registration
      @online_application.registration_type = 'group'
    elsif @online_application.application_group.family_registration
      @online_application.registration_type = 'family'
    else
      @online_application.registration_type = 'single'
    end

    if step == :group or step == :family or step == :detail or step == :dates_and_events or step == :visa or step == :finances or step == :confirmation
      # Because we use the @application_group object for these steps, we need to
      # make sure to explicitly update the status field which lives on the primary
      # applicant object.
      @online_application.status = step.to_s
      @online_application.save(:validate => false)
    end

    populate_ethereal_variables
    render_wizard
  end

  def add_family_member
    add_member
    @application_group.online_applications.build()
    render "add_family_member", :layout => false
  end

  def add_group_member
    add_member
    # The form allows setting an alternative permament address for group members
    @application_group.online_applications.build({:relation => 'other'})
    @application_group.online_applications.first.build_permanent_address if @application_group.online_applications.first.permanent_address.nil?
    render "add_group_member", :layout => false
  end

  def update
    if not @application_group.online_applications.include?(@online_application) then
      # Something funky is going on here. Most likely, they have already submitted this application.
      redirect_to :error
      return
    end

    # This is effectively optimistic locking. Deals with people who open multiple copies of the form in various
    # stages on different browser tabs and then submit them interchangeably. Yes, this is pretty common.
    if ((params.has_key?('application_group') and
         params[:application_group].has_key?('lock_version') and
         params[:application_group][:lock_version] != @application_group.lock_version.to_s) or
        (params.has_key?('online_application') and
         params[:online_application].has_key?('lock_version') and
        params[:online_application][:lock_version] != @online_application.lock_version.to_s))
      # This is not the latest copy of the application group. Tell the user and reload the page.
      flash[:error] = "The application was modified since this page was loaded. The changes you just submitted could not be saved. Please try again."
      redirect_to request.path
      return
    else
      params[:application_group].delete('lock_version') if params.has_key?('application_group') and params[:application_group].has_key?('lock_version')
      params[:online_application].delete('lock_version') if params.has_key?('online_application') and params[:online_application].has_key?('lock_version')
    end

    if step != :group and step != :family and step != :detail and step != :dates_and_events and step != :visa and step != :finances and step != :confirmation and step != :payment
      params[:online_application][:status] = step.to_s
      params[:online_application][:status] = 'complete' if step == steps.last

      if not @online_application.update_attributes(params[:online_application])
        populate_ethereal_variables
      else
        if step == :personal and @online_application.relation == 'primary applicant'
          @online_application.application_group.group_registration = (@online_application.registration_type == 'group' ? true : false)
          @online_application.application_group.family_registration = (@online_application.registration_type == 'family' ? true: false)
          # We can't validate the group here yet, because the group name is probably not set yet.
          # We can't make the group name validation conditional on the step of this form
          # because we need to consult the primary application online_application for the step
          # and that record is not accessible yet when the applcation_group object is being validated.
          # It would be, if inverse_of worked for has_many, which it does not (as of rails 3.2.21)...
          @online_application.application_group.save(:validate => false)
        end
      end
    else
      if step == :finances
        # The rate radio button should set the student boolean to true if that rate is selected
        params[:application_group]['online_applications_attributes'].each do |key,val|
          if val['rate'] == 'student'
            val['student'] = 1
          else
            val['student'] = 0
          end
        end
        params[:application_group][:online_applications_attributes].each do |k,v|
          if params[:application_group][:payment_required].nil? then
            params[:application_group][:payment_required] = 0
          end
          params[:application_group][:payment_required] += v[:calculated_registration_fee].to_i
        end
      end
      if step == :group and params[:application_group].has_key?('online_applications_attributes')
        # Do not save permanent address information if the 'different address' checkbox is not set
        params[:application_group]['online_applications_attributes'].each do |key,val|
          val['permanent_address_attributes']['_destroy'] = true if val['different_address'] != '1'
        end
      end

      if step == :detail
        # Walk the online_application_languages entries. If there are any that have an id
        # (i.e. they were previously saved) but no longer have a value (i.e. the user went
        # back and set language and proficiency to 'choose one', and saved again, then
        # mark that entry as to be destroyed. I surprised that the ":reject_if => :all_blank"
        # option on the accepts_nested_attributes_for :online_application_languages line in
        # the online_application model does not catch this...
        params[:application_group][:online_applications_attributes].each do |k,v|
          if params[:application_group][:online_applications_attributes][k].has_key?('online_application_languages_attributes')
            params[:application_group][:online_applications_attributes][k]['online_application_languages_attributes'].each do |k2,v2|
              if v2.has_key?('id') and v2.has_key?('language_id') and v2['language_id'].empty? and
                 v2.has_key?('proficiency') and v2['proficiency'].empty?
                v2['_destroy'] = true
              end
            end
          end
        end
      end

      if step == :dates_and_events
        if params[:application_group][:online_applications_attributes]['0']['heard_about'] == 'I have been to Caux before'
          params[:application_group][:online_applications_attributes]['0']['previous_visit'] = true
        end

        params[:application_group][:online_applications_attributes].each do |k,v|

          # If no check boxes are checked, the form does not return those fields.
          # Handle that here, making sure that any training programs previously
          # selected will be removed.
          if params[:application_group][:online_applications_attributes][k].has_key?('online_application_training_programs_attributes')
            params[:application_group][:online_applications_attributes][k]['online_application_training_programs_attributes'].each do |k2,v2|
              if v2['selected'] != '1'
                v2['_destroy'] = true
              elsif v2 and not v2.has_key?('id') and params[:application_group][:online_applications_attributes][k].has_key?('id')
                # It turns out that update_attributes (below) does not add *new* online_application_training_programs,
                # if the online application already has some online_application_training_programs (i.e. when the user came back
                # to the 'Stay in Caux' page after having saved it and added a new training_program. So, we add these explicitly
                # here, and then set the id field to make update_attributes do an additional refresh of the
                # application_group object.
                oatp = OnlineApplicationTrainingProgram.new(v2)
                oatp.online_application_id = params[:application_group][:online_applications_attributes][k]['id']
                # Save but guard against race conditions (or double form submissions, Edge seems to have a knack for those)
                begin
                  oatp.save
                  v2['id'] = oatp.id
                rescue
                  v2['id'] = OnlineApplicationTrainingProgram.where(:online_application_id => params[:application_group][:online_applications_attributes][k]['id'], :training_program_id => v2[:training_program_id]).first.id
                end
              end
            end
          end
          # Make sure we delete online_application_conferences records that are not selected

app/helpers/online_applications_helper.rb
module OnlineApplicationsHelper
end

app/views/online_applications/_conference_fees.html.erb
         <table class="af_block">
           <tr>
             <td colspan="2" align="center"><span class="af_normtitle"><%=t :conference_fees %></span></td>
           </tr>
           <tr>
             <td colspan="2">
               <div class="field">
                 <%=t :more_information_about_conference_fees_html %><br />
                 <input type="hidden" id="family_discount" name="family_discount" value="<%= @family_discount %>">
                 <div class="show_for_primary_applicant">
                 <%= f.check_box :family_discount %> <%= f.label :family_discount, t(:i_travel_with_my_family) %><br />
                 </div>
                 <div class="hide_for_children">
                   <%= f.check_box :sent_by_employer %> <%=f.label :sent_by_employer, t(:i_am_sent_by_my_employer) %><br />
                 </div>
                 <%= f.check_box :student %> <%=f.label :student, t(:i_am_a_student) %><br />
               </div>
             </td>
           </tr>
           <tr>
             <td>
               <table class="sponsors_table">
                 <tr>
                   <th>
                     <div class="field">
                       <label>&nbsp;</label>
                     </div>
                   </th>
                   <th>
                     <div class="field">
                       <label><%=t :sponsors_nights %></label>
                     </div>
                   </th>
                   <th>
                     <div class="field">
                       <label><%=t :rate_per_night %></label>
                     </div>
                   </th>
                   <th align="right">
                     <div class="field">
                       <label><%=t :total %></label>
                     </div>
                   </th>
                 </tr>
                 <tr>
                   <td>
                     <div class="field">
                       <%=t :cost_of_your_stay %>
                     </div>
                   </td>
                   <td>
                     <div class="field">
                       <div id="nights_visible"></div>
                     </div>
                   </td>
                   <td>
                     <div class="field">
                       CHF <span id="rate_per_night_visible"></span><input type="hidden" id="rate_per_night" name="rate_per_night">
                     </div>
                   </td>
                   <td align="right">
                     <div class="field">
                       CHF <span id="total_nights_visible"></span><input type="hidden" id="total_nights" name="total_nights">
                     </div>
                   </td>
                 </tr>
                 <tr>
                   <td>
                     <div class="field">
                       <%=t :registration_fee %>
                     </div>
                   </td>
                   <td>
                     <div class="field">
                     </div>
                   </td>
                   <td>
                     <div class="field">
                     </div>
                   </td>
                   <td align="right">
                     <div class="field">
                       CHF <span id="registration_fee_visible"></span><input type="hidden" id="registration_fee" name="registration_fee">
                     </div>
                   </td>
                 </tr>
                 <tr>
                   <td colspan="4">
                   <hr>
                   </td>
                 </tr>
                 <tr>
                   <td colspan="4">
                     <%=t :nightly_contribution_html %>
                   </td>
                 </tr>
                 <tr>
                   <th>
                     <div class="field">
                       <label><%=t :sponsors_name %></label>
                     </div>
                   </th>
                   <th>
                     <div class="field">
                       <label><%=t :sponsors_nights %></label>
                     </div>
                   </th>
                   <th colspan="2" align="right">
                     <div class="field">
                       <label><%=t :sponsors_amount %></label>
                     </div>
                   </th>
                 </tr>
                 <%= f.fields_for :sponsors do |sf| -%>
                 <tr>
                   <td>
                     <div class="field">
                       <%= sf.text_field :name %>
                     </div>
                   </td>
                   <td>
                     <div class="field">
                       <%= sf.text_field :nights, :size => 3 %>
                     </div>
                   </td>
                   <td colspan="2" align="right">
                     <div class="field">
                       CHF <%= sf.text_field :amount, :size => 3 %>
                     </div>
                   </td>
                 </tr>
                 <% end -%>
                 <tr>
                   <td colspan="4">
                   <hr>
                   </td>
                 </tr>
                 <tr>
                   <td colspan="4" align="center">
                     <div id="personalContribution">
                       <h2><%=t :please_check_total_html %></h2><br/>
                       <table width="100%">
                         <tr>
                           <td align="left">
                             <%=t :personal_contribution_html %>
                           </td>
                           <td align="right">
                             <strong>CHF <span id="total_automatic">0</span></strong><br />
                           </td>
                         </tr>
                       </table>
                     </div>
                   </td>
                 </tr>


                 </td>
                 </tr>
               </table>
             </td>
           </tr>
           <tr colspan="2">
             <td>
                 <%= f.hidden_field :calculated_nights %><br />
                 <%= f.hidden_field :calculated_night_rate, :size => 6 %><br />
                 <%= f.hidden_field :calculated_registration_fee, :size => 6 %><br />
                 <%= f.hidden_field :calculated_total_personal_contribution, :size => 6 %><br />
                 <%= f.hidden_field :calculated_rate_and_fee_details %><br />
             </td>
           </tr>
         </table>

app/views/online_applications/_contact_information.html.erb
         <table class="af_block">
           <tr>
             <td colspan="2" align="center"><span class="af_normtitle"><%=t :contact_information %></span></td>
           </tr>
           <tr>
             <td>
               <div class="field">
                 <span class="af_star show_for_primary_applicant">*</span><%= f.label :email, t(:email) %><br />
                 <%= f.text_field :email %>
               </div>
             </td>
             <td>
               <div class="field">
                 <span class="af_star show_for_primary_applicant">*</span><%= f.label :email_confirmation, t(:email_confirmation) %><br />
                 <% if not @online_application.email.nil? and not @online_application.email.empty? -%>
                   <%= f.text_field :email_confirmation, { :value => @online_application.email } %>
                 <% else -%>
                   <%= f.text_field :email_confirmation %>
                 <% end -%>
               </div>
             </td>
           </tr>
           <tr>
             <td>
               <div class="field">
                 <span class="af_star show_for_primary_applicant">*</span><%= f.label :telephone, t(:telephone) %><br />
                 <%= f.text_field :telephone %>
               </div>
             </td>
             <td>
               <div class="field">
                 <%= f.label :cellphone, t(:cellphone) %><br />
                 <%= f.text_field :cellphone %>
               </div>
             </td>
           </tr>
           <tr>
             <td>
               <div class="field">
                 <span class="af_star" id="fax_required" style="display: none">*</span><%= f.label :fax, t(:fax ) %><br />
                 <%= f.text_field :fax %>
               </div>
             </td>
             <td>
               <div class="field">
                 <%= f.label :work_telephone, t(:work_telephone) %><br />
                 <%= f.text_field :work_telephone %>
               </div>
             </td>
           </tr>
           <tr class="show_for_primary_applicant">
             <td colspan="2">
               <div class="field">
                 <span class="af_star">*</span><%= f.label :confirmation_letter_via, t(:confirmation_letter_via) %><br />
                 <%= f.radio_button :confirmation_letter_via, 'email', :checked => true %> <%=t :confirmation_letter_via_email %>
                 <%= f.radio_button :confirmation_letter_via, 'post' %> <%=t :confirmation_letter_via_post %>
                 <%= f.radio_button :confirmation_letter_via, 'fax' %> <%=t :confirmation_letter_via_fax %>
                 <%= f.radio_button :confirmation_letter_via, 'correspondence_address' %> <%=t :confirmation_letter_via_correspondence_address %>
               </div>
             </td>
           </tr>
         </table>

app/views/online_applications/_correspondence_address.html.erb
         <%= f.fields_for :correspondence_address do |af| %>
         <table class="af_block">
           <tr>
             <td colspan="2" align="center"><span class="af_normtitle"><%=t :correspondence_address %></span></td>
           </tr>
           <tr>
             <td colspan="2">
               <div class="field">
                 <span class="af_star">*</span><label><%=t :addresses_street1 %></label><br />
                 <%= af.text_field :street1 %><br />
                 <%= af.text_field :street2 %><br />
                 <%= af.text_field :street3 %>
               </div>
             </td>
           </tr>
           <tr>
             <td colspan="2">
               <div class="field">
                 <span class="af_star">*</span><%=af.label :city, t(:addresses_city) %><br />
                 <%= af.text_field :city %>
               </div>
             </td>
           </tr>
           <tr>
             <td colspan="2">
               <div class="field">
                 <%= af.label :postal_code, t(:postal_code) %><br />
                 <%= af.text_field :postal_code %>
               </div>
             </td>
           </tr>
           <tr>
             <td colspan="2">
               <div class="field">
                 <%=af.label :state, t(:state) %><br />
                 <%= af.text_field :state %>
               </div>
             </td>
           </tr>
           <tr>
             <td>
               <div class="field">
                 <span class="af_star">*</span><%= af.label :country_id, t(:addresses_country_id) %><br />
                 <%= af.select(:country_id, @countries, {:include_blank => t(:choose_one)}) %>
               </div>
             </td>
             <td>
                <div class="field" id="correspondence_address_other_country" style="display: none">
                 <span class="af_star">*</span><%= af.label :other_country, t(:other_country) %><br />
                 <%= af.text_field :other_country %>
               </div>
             </td>
           </tr>
           <tr>
             <td colspan="2">
               <div class="field">
                 <span class="af_star">*</span><%= af.label :valid_from, t(:valid_from) %><br />
                 <% field_with_errors @online_application.correspondence_address, :valid_from do -%>
                   <%= af.date_select :valid_from, :include_blank => :true, :start_year => Time.now.year, :end_year => Time.now.year + 1 %>
                 <% end -%>
               </div>
             </td>
           </tr>
           <tr>
             <td colspan="2">
               <div class="field">
                 <span class="af_star">*</span><%= af.label :valid_until, t(:valid_until) %><br />
                 <% field_with_errors @online_application.correspondence_address, :valid_until do -%>
                   <%= af.date_select :valid_until, :include_blank => :true, :start_year => Time.now.year, :end_year => Time.now.year + 1 %>
                 <% end -%>
               </div>
             </td>
           </tr>
         </table>
         <% end %>

app/views/online_applications/_form.html.erb
<%= form_for(@online_application) do |f| %>

<table class="tablerow">
<tr>
  <td class="pagetitle">
    <h1><%= t(:title) %></h1>
  </td>
</tr>
</tr>
<tr>
   <td class="af_center">
    <%= error_messages_for :online_application, :header_message => 'Error:', :message => nil %>
   </td>
</tr>
<tr>
  <td class="af_justify">
<p>
<%=t :intro_part_1_html %>
<%=t :intro_part_1b_html %>
<script language="JavaScript"> 
<!--
document.write ('<a href="mai')
document.write ('lto:reservation')
document.write ('&#64;')
document.write ('caux.ch"><%=t :intro_part_1c %></a>.')
// -->
</script>
<%=t :intro_part_2_html %>
</p>

<p align="left">
<%=t :intro_part_3 %>
</p>
<p align="left">
<%=t :intro_part_4_html %>
</p>
</td>
</tr>

<tr>
  <td valign="top">
    <table>
      <tr>
        <td colspan="2">
          <%= render 'personal_information', :f => f %>
      </td>
      </tr>
      <tr class="hide_for_children">
        <td colspan="2">
          <%= render 'contact_information', :f => f %>
        </td>
      </tr>
      <tr class="hide_for_family_members">
        <td colspan="2">
          <%= render 'permanent_address', :f => f %>
        </td>
      </tr>
      <tr class="correspondence_address_required" style="display:none">
        <td colspan="2">
          <%= render 'correspondence_address', :f => f %>
        </td>
      </tr>
      <tr>
        <td colspan="2">
          <%= render 'stay_in_caux', :f => f %>
        </td>
      </tr>
      <tr>
        <td colspan="2">
          <%= render 'visa', :f => f %>
        </td>
      </tr>
      <tr>
        <td colspan="2">
          <%= render 'participation', :f => f %>
        </td>
      </tr>
      <tr>
        <td colspan="2">
          <%= render 'name_badge', :f => f %>
        </td>
      </tr>
      <tr>
        <td colspan="2">
          <%= render 'conference_fees', :f => f %>
        </td>
      </tr>
      <tr>
        <td colspan="2">
          <%= render 'remarks', :f => f %>
        </td>
      </tr>
      <tr>
        <td colspan="2" align="center">
          <div class="actions">
            <%= f.submit t(:proceed) %>
          </div>
        </td>
      </tr>
    </table>
  </td>
</tr>
</table>
<% end -%>

app/views/online_applications/_name_badge.html.erb
         <table class="af_block">
           <tr>
             <td colspan="2" align="center"><span class="af_normtitle"><%=t :name_badge %></span></td>
           </tr>
           <tr>
             <td colspan="2">
                 <%=t :badge_explanation %>
             </td>
           </tr>
           <tr>
             <td>
               <div class="field">
                 <span class="af_star">*</span><%= f.label :badge_firstname, t(:firstname) %><br />
                 <%= f.text_field :badge_firstname %>
               </div>
             </td>
             <td>
               <div class="field">
                 <span class="af_star">*</span><%= f.label :badge_surname, t(:surname) %><br />
                 <%= f.text_field :badge_surname %>
               </div>
             </td>
           </tr>
           <tr>
             <td colspan="2">
               <div class="field">
                 <span class="af_star">*</span><%= f.label :badge_country, t(:country) %><br />
                 <%= f.text_field :badge_country, :size => 60 %>
               </div>
             </td>
           </tr>
         </table>

app/views/online_applications/_permanent_address.html.erb
         <%= f.fields_for :permanent_address do |af| %>
         <table class="af_block">
           <tr>
             <td colspan="2" align="center"><span class="af_normtitle"><%=t :permanent_address %></span></td>
           </tr>
           <tr>
             <td colspan="2">
               <div class="field">
                 <span class="af_star">*</span><label><%=t :addresses_street1 %></label><br />
                 <%= af.text_field :street1 %><br />
                 <%= af.text_field :street2 %><br />
                 <%= af.text_field :street3 %>
               </div>
             </td>
           </tr>
           <tr>
             <td colspan="2">
               <div class="field">
                 <span class="af_star">*</span><%=af.label :city, t(:addresses_city) %><br />
                 <%= af.text_field :city %>
               </div>
             </td>
           </tr>
           <tr>
             <td colspan="2">
               <div class="field">
                 <%= af.label :postal_code, t(:postal_code) %><br />
                 <%= af.text_field :postal_code %>
               </div>
             </td>
           </tr>
           <tr>
             <td colspan="2">
               <div class="field">
                 <%=af.label :state, t(:state) %><br />
                 <%= af.text_field :state %>
               </div>
             </td>
           </tr>
           <tr>
             <td>
               <div class="field">
                 <span class="af_star">*</span><%= af.label :country_id, t(:addresses_country_id) %><br />
                 <%= af.select(:country_id, @countries, {:include_blank => t(:choose_one)}) %>
               </div>
             </td>
             <td>
                <div class="field" id="permanent_address_other_country" style="display: none">
                 <span class="af_star">*</span><%= af.label :other_country, t(:other_country) %><br />
                 <%= af.text_field :other_country %>
               </div>
             </td>
           </tr>
         </table>
         <% end %>

app/views/online_applications/_remarks.html.erb
         <table class="af_block">
           <tr>
             <td colspan="2" align="center"><span class="af_normtitle"><%=t :remarks %></span></td>
           </tr>
           <tr>
             <td colspan="2">
               <div class="field">
                 <%= f.label t(:remarks) %><br />
                 <%= f.text_area :remarks, :cols => 100, :rows => 5 %>
               </div>
             </td>
           </tr>
         </table>

app/views/online_applications/edit.html.erb
<%= render 'form' %>

app/views/online_applications/index.html.erb
<table class="tablerow">
<tr>
  <td class="pagetitle">
    <h1><%=t :your_application_title %></h1>
  </td>
</tr>
</tr>
<tr>
  <td class="af_justify">


<table class="application_list">
  <tr>
    <th></th>
    <th><%=t :firstname %></th>
    <th><%=t :surname %></th>
    <th><%=t :gender %></th>
    <th><%=t :arrival %></th>
    <th><%=t :departure %></th>
    <th></th>
    <th></th>
  </tr>

<% @online_applications.each do |online_application| %>
  <tr>
    <td><%= online_application.relation == 'primary applicant' ? '' : t(online_application.relation) %></td>
    <td><strong><%= online_application.firstname %></strong></td>
    <td><strong><%= online_application.surname %></strong></td>
    <td><%= online_application.gender == 1 ? t(:female) : t(:male) %></td>
    <td><%= online_application.arrival.to_s(:pretty) %></td>
    <td><%= online_application.departure.to_s(:pretty) %></td>
    <td><%= link_to t(:edit), build_path(Wicked::FIRST_STEP, :online_application_id => online_application.id) %></td>
    <td><%= link_to t(:remove), online_application, :confirm => t(:are_you_sure), :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<p class="prominent">
<%=t :application_not_yet_submitted_html %>
</p>

<table>
<tr>
<td>
<%= button_to t(:add_a_person_to_this_application), new_build_path, :method => :get %>
</td>
<td>
<%= button_to t(:submit_this_application), submit_application_group_path, :method => :get %>
</td>
</tr>
</table>

  </td>
</tr>
</table>

app/views/online_applications/new.html.erb
<%= render 'form' %>